# Generated by Django 4.0.4 on 2022-05-28 17:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dkoperasi', '0001_initial'),
        ('dakun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerakhirInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_date', models.DateField(default=datetime.datetime.now)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dakun.akun')),
                ('koperasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dkoperasi.koperasi')),
            ],
            options={
                'unique_together': {('koperasi', 'input_date', 'akun')},
            },
        ),
        migrations.CreateModel(
            name='AkunNominal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_date', models.DateField(default=datetime.datetime.now)),
                ('nominal', models.BigIntegerField()),
                ('tahun', models.IntegerField(default=2022)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dakun.akun')),
                ('koperasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dkoperasi.koperasi')),
            ],
            options={
                'unique_together': {('koperasi', 'akun', 'tahun')},
            },
        ),
    ]
