# Generated by Django 4.0.4 on 2022-05-28 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelkrat', '0003_alter_akunnominal_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akunnominal',
            name='tahun',
        ),
    ]
