# Generated by Django 4.0.4 on 2022-05-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dakun', '0001_initial'),
        ('dkoperasi', '0003_alter_koperasi_options_alter_type_options'),
        ('pelkrat', '0004_remove_akunnominal_tahun'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='akunnominal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='akunnominal',
            name='tahun',
            field=models.IntegerField(default=2022),
        ),
        migrations.AlterUniqueTogether(
            name='akunnominal',
            unique_together={('koperasi', 'akun', 'tahun')},
        ),
    ]
