# Generated by Django 4.0.4 on 2022-06-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelkrat', '0005_alter_akunnominal_unique_together_akunnominal_tahun_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='akunnominal',
            options={'ordering': ['koperasi', 'akun', 'input_date']},
        ),
    ]
