# Generated by Django 4.0.4 on 2022-05-28 17:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Koperasi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('koperasi', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('type', models.ManyToManyField(blank=True, to='dkoperasi.type')),
            ],
        ),
    ]
