# Generated by Django 4.0.4 on 2022-05-28 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dkoperasi', '0002_rename_koperasi_koperasi_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='koperasi',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['name']},
        ),
    ]
