# Generated by Django 4.0.4 on 2022-05-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dkoperasi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_1', models.IntegerField()),
                ('code_2', models.IntegerField()),
                ('code_3', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('debit_credit', models.CharField(blank=True, choices=[('+', 'Debit'), ('-', 'Kredit')], max_length=1)),
                ('koperasi_type', models.ManyToManyField(blank=True, to='dkoperasi.type')),
            ],
            options={
                'ordering': ['code_1', 'code_2', 'code_3'],
            },
        ),
    ]
