# Generated by Django 4.0.4 on 2022-05-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dakun', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akun',
            name='code_1',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='akun',
            name='code_2',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='akun',
            name='code_3',
            field=models.IntegerField(blank=True),
        ),
    ]
