# Generated by Django 4.0.4 on 2022-06-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dakun', '0003_alter_akun_code_1_alter_akun_code_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='akun',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
