# Generated by Django 4.0.4 on 2022-06-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dakun', '0004_akun_is_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akun',
            name='code_1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='akun',
            name='code_2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='akun',
            name='code_3',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
